name: almabroorhajj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^2.26.0
  firebase_auth: 4.16.0
  firebase_auth_web: ^5.9.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.3.0
  firebase_storage_web: ^3.6.24
  firebase_messaging: ^14.9.4
  flutter_riverpod: ^2.3.0
  flutter_local_notifications: ^14.0.1
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.0
  intl: ^0.18.0
  video_player: ^2.6.0
  youtube_player_flutter: ^8.1.0
  flutter_html: ^3.0.0
  firebase_analytics: ^10.10.7
  provider: ^6.1.5+1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_local_notifications_linux: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
